### ISSUE TITLE
check fail

### ISSUE THREAD

**Issue by robinandeer** [Clinical-Genomics/trailblazer#10]
Trailblazer should be able to check results for a failed analysis:

1. `/families/[FAMILY]/analysis/*/*_qc_metrics.yaml`
    1. `program -> plink_gender_check -> [SAMPLE] = FAIL/PASS`
        1. `families/[FAMILY]/analysis/*/bwa/casecheck/plink/*.sexcheck`
        1. `families/[FAMILY]/analysis/*/bwa/casecheck/peddy/*.sex_check.csv`
        1. `sample -> [SAMPLE] -> [ACC3247A1]_lanes_[1-9]* -> chanjo_sexcheck -> gender -> male/female`
        1. `families/[FAMILY]/analysis/[SAMPLE]/bwa/coveragereport/*_lanes_[1-9]*_sorted_md_brecal_sex.tsv`
    1. `evaluation -> markduplicates - FAILED:markduplicates_fraction_duplicates:[FLOAT]` AND to get sample `sample -> [SAMPLE] -> [SAMPLE]_lanes_* -> markduplicates -> fraction_duplicates -> [FLOAT]`
        1. check source in status/LIMS, saliva?
        1. `sample -> [SAMPLE] -> [SAMPLE].*.lane[1-9] -> bamstats -> percentage_mapped_reads -> [FLOAT]`
        1. `sample -> [SAMPLE] -> [SAMPLE]_lanes_[1-9]* -> collecthsmetrics -> MEAN_TARGET_COVERAGE/PCT_TARGET_BASES_10X -> [FLOAT]`

Plink sexcheck:
```
          FID         IID       PEDSEX       SNPSEX       STATUS            F
  majormammal   ACC3247A1            1            0      PROBLEM       0.4852
  majormammal   ACC3247A2            2            2           OK      -0.7645
  majormammal   ACC3247A3            1            0      PROBLEM       0.5041
```

Peddy sexcheck:
```
error,het_count,het_ratio,hom_alt_count,hom_ref_count,ped_sex,predicted_sex,sample_id
False,23595,0.5956,39613,30875,male,male,ACC3247A1
False,50853,1.894,26856,20145,female,female,ACC3247A2
False,22706,0.5839,38884,32840,male,male,ACC3247A3
```

Chanjo sexcheck (tabs):
```
#X_coverage\tY_coverage\tsex
18.9341\t11.2652\tmale
```

**Comment by moonso** [comment]
I guess we can close this since it is three years old

**Comment by henrikstranneheim** [comment]
Also I just removed the CLI command
