### ISSUE TITLE
Suggestion: Column with "Ticket Number" in trailblazer

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/trailblazer#108]
It would be more convenient for production if there would be a column in trailblazer that showed ticket number.

If production would see the ticket number in trailblazer it would allow us to easier deliver analyses ticket-by-ticket, which would be much faster than jumping around between tickets. This update would also allow us to easier know when a ticket can be closed, since we finish it as once.

I have talked to Kalle and Emma, and both agree this is a good idea.

**Comment by Mropat** [comment]
We could pass this info along from cg
@henrikstranneheim - Do you think this information should be stored/provided by Trailblazer?

**Comment by henningonsbring** [comment]
I close this issue, ticket number is now included, perhaps we should change where it is displayed, but I think production should use the new trailblazer for a while and then make up our minds about which updates are most important. Then we will come back with what we think.

**Comment by Mropat** [comment]
This can stay as we sleep on it. It is not possible to move where ticket is displayed without changes to tb

**Comment by fevac** [comment]
It would be nice to display the ticket number in the main page on trailblazer. It be very helpful for delivery and would speed up the process.

**Comment by GustavLagneborgScilifelab** [comment]
I talked to @elevu about it, and if the getAnalyses function on trailblazer included the ticket number, it could be added. Since I have development this and next week I can look into it :)

**Comment by GustavLagneborgScilifelab** [comment]
2 PRs will have to be craeted, one to make sure that CG also sends the ticket number to trailblazer, and one in the trailblazer repo that makes sure that it can store the ticket number for an analysis and then send it to cig

1. In CG repo - Add ticket information to the add_pending_analysis function so it is sent to trailblazer - https://github.com/Clinical-Genomics/cg/pull/1629
2. In Trailblazer repo - Store the ticket number in the trailblazer database for models.analysis and then add ticket number to the function get_analysis so Cigrid also gets the ticket information

**Comment by GustavLagneborgScilifelab** [comment]
Both PRs can now be reviewed!

**Comment by GustavLagneborgScilifelab** [comment]
This is now implemented, closing issue
