### ISSUE TITLE
Separate the frontend from the backend

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/trailblazer#118]
Has we have been discussing before I think it is a good idea to rewrite and separate the frontend from the backend in the Trailblazer project.
Why? It would make it much simpler to develop new features. The current nuxt project is using a lot of deprecated packages which causes several bugs and they are hard to change.

I build a first draft of the project in this repo: https://github.com/elevu/trailblazer-ui/
The website is currently deployed to google firebase via github actions here https://trailblazer-test.web.app/
Right now you will not be able to use any backend on the firebase app since the ip is not whitelisted for authentication.
Here is the deployment pipeline https://github.com/elevu/trailblazer-ui/runs/1085930533?check_suite_focus=true
<img width="311" alt="Screen Shot 2020-09-08 at 14 47 48" src="https://user-images.githubusercontent.com/6919697/92478323-49b93980-f1e2-11ea-8df4-aa563d2fad5e.png">

I think this deployment a solution that works both temporary or long term.
[Google firebase](https://firebase.google.com/) frontend deployment is extremely easy to set up, all it takes is a github action and we already have a Clinical Genomics account.
If we want to move away from firebase once we make a decision on how to proceed with containers after the clinical-db era, we can really quickly leave firebase as well.
The deployment would be free for us since we have really low usage, see [pricing](https://firebase.google.com/pricing) for info.
If @eriksjolund @patrikgrenfeldt @jemten @henrikstranneheim agree on this solution, next steps will be:
-  adding the new repo and the firebase projects trailblazer-stage and trailblazer to the clinical genomics organization (on github and google). 
- Run in contemporary both the new and old Trailblazer website for a couple of weeks to make sure everything works as expected
- Delete the old UI from the trailblazer repo and point the trailblazer URL to the the new repo.

Let me know what you think!

**Comment by henrikstranneheim** [comment]
I think this would be great Let's try it out for one or 2 weeks in parallel with the current prod ui. 
@elevu Could you switch from your own repo to clinical genomics for the test phase

**Comment by jemten** [comment]
Sounds great! I agree with Henrik that we should run the two ui:s in parallel for a short while

**Comment by elevu** [comment]
Done!
