### ISSUE TITLE
Unable to create analysis config (not pedigree) when target coverage is 0

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/trailblazer#12]
Trailblazer throws an error when you try to start an analysis of WGXCUSC000 that has been set to 0 expected coverage. It just says that there is no expected coverage for the sample. Changing expected coverage to 1 solved the issue.

After looking a bit more closely it might be mip that's causing the issue:
`MIP - Could not find value for ADM1524A19 for parameter '--expected_coverage'`
`  File "/mnt/hds/proj/bioinfo/SERVER/miniconda/envs/prod170926/lib/python3.6/site-packages/trailblazer/mip/start.py", line 44, in __call__
    raise MipStartError('error starting analysis, check the output')
trailblazer.exc.MipStartError: error starting analysis, check the output`

**Comment by ingkebil** [comment]
Still needed?

**Comment by emiliaol** [comment]
So according to HS we can get rid of this issue by not including the coverage in the pedigree file for externally sequenced sample (Apptag EXX, WGX). See https://github.com/Clinical-Genomics/MIP/issues/606. And that's a trailblazer thing I think. We normally do it using `cg analysis config`. 

But I also know that there is a check to skip evaluation is sample is external when starting with cg. Perhaps this is the problem, if I have to start with trailblazer it will not pick up on the external flag in status db and thus try include the evaluation?

**Comment by ingkebil** [comment]
That is correct. TB does not know about statusdb nor about application tags. It knows about MIP output and about TB :)

This cannot be solved 'automatically', meaning that we will have to add a param to exclude that sample from the pedigree. Some delving into the code needs to be performed to make sure that is the way to go.

**Comment by emiliaol** [comment]
Or maybe we should just leave it as it is and NOT start analysis using TB. If we have to we just need to take this into consideration?

**Comment by henrikstranneheim** [comment]
Analyses are now started using only cg. This seems solved - reopen if you disagree
