### ISSUE TITLE
Parameter is_visible not working when making requests to trailblazer-api

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/trailblazer#122]
Requests like this one:
https://trailblazer-api-stage.scilifelab.se/api/v1/analyses?is_visible=false
do not work, the backend is returning all the analyses, even visible ones. I assume this is a bug since in the old UI there are several of these requests therefore I guess they used to work. It would be nice to have this option to more easily filter on analyses.

**Comment by Mropat** [comment]
This was never possible AFAIK. Would you like me to add it?

**Comment by elevu** [comment]
it is not urgent at all but it would be nice to have it!

**Comment by elevu** [comment]
Maria showed me that it works on is_visible=true. This is enough! Closing the issue
