### ISSUE TITLE
Make the cause of failure visible again from Analyses view

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/trailblazer#128]
Before we could se the cause of failure directly, now we have to go into the TB-id to see the program that has failed. I would like to see the cause of failure more directly now it's too much clicking around and the filtering has to be done again after each time.

**Comment by elevu** [comment]
Ok, so for example for this failed case is it the info "picardtools_collecthsmetrics" that you want to see?
![Screen Shot 2020-09-30 at 11 47 40](https://user-images.githubusercontent.com/6919697/94670413-d010f900-0312-11eb-824b-17c0b93f711b.png)

**Comment by vwirta** [comment]
Exactly. It was previously visible by hoovering over the FAILED logo, but other ways of showing this is also ok

**Comment by elevu** [comment]
>Exactly. It was previously visible by hoovering over the FAILED logo, but other ways of showing this is also ok

Added, in prod! Displaying when hoovering.

![Screen Shot 2020-09-30 at 13 32 07](https://user-images.githubusercontent.com/6919697/94680016-5fbda400-0321-11eb-814c-660f3a57a8eb.png)

**Comment by emmser** [comment]
Great! Thanks a lot!
