### ISSUE TITLE
Divide Stats fails in Type (WES and WGS)

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/trailblazer#136]
Divide the fails of different programs in types of samples since the WGS and WES often fails on different things. It's nice to be able to pick up type-specific fails in an easy way.

**Comment by elevu** [comment]
Is it ok if I add a filter by type (WGS and WES) in the Stats page?

**Comment by Mropat** [comment]
That is OK!
Do you need anything from the backend in order to achieve this, or is the jobs endpoint enough?

**Comment by Mropat** [comment]
Closing this until stats are ready to return to GUI
