### ISSUE TITLE
Expose is_primary field when returning list of analyses

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/trailblazer#137]
According to this discussion https://github.com/Clinical-Genomics/cgp-reruns/issues/2
When returning a list of analyses, trailblazer should also return the field "is_primary": which is extracted from StatusDB.

**Comment by Mropat** [comment]
This field is only available in cg for analyses that were completed. For analyses that are started, are tracked in trailblazer, but haven't been stored in housekeeper yet, there simply isn't an analysis entry in CG yet. So any analysis in tb that isn't an analysis on cg yet should be primary...
