### ISSUE TITLE
Add endpoints that return re-runs statistics

### ISSUE THREAD

**Issue by elevu** [Clinical-Genomics/trailblazer#138]
Add endpoint that takes a date range and returns a list of costumers with how many re-runs have been done by each customer. As discussed here https://github.com/Clinical-Genomics/cgp-reruns/issues/2

**Comment by Mropat** [comment]
This question is better suited for cg - all necessary information can be queried from status_db. Trailblazer doe not have access to necessary data to support this yet

**Comment by Mropat** [comment]
Not possible to do with current architecture
