### ISSUE TITLE
[Quesition] hide non-production samples/cases

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/trailblazer#155]
Is there a way to mass-hide non-production cases/samples via CLI? I do run quite a number of analyses and it might clutter production. Ultimately I prefer to auto-hide in TB when running samples. Example:
![image](https://user-images.githubusercontent.com/1086877/99044277-cde7be80-258f-11eb-83c9-1187b07507ae.png)

As a user I have to login to UI and hide manually, which is not practical at high number of cases.

**Comment by hassanfa** [comment]
If this is more related to frontend, please move it there.

**Comment by henrikstranneheim** [comment]
@hassanfa Why do you run non-production samples in production? This does not seem to be the right thing to do. Would it be possible to run this in your own development env or at least in stage?

**Comment by hassanfa** [comment]
They are production, but not for customer.

Example: the samples above are for investigating adapter read-through and insert size estimation.

**Comment by hassanfa** [comment]
@henrikstranneheim  I hit enter button too quickly, here is the rest:

It is not just these:
1. Sometimes we also do downsample and add downsampled fastq files to housekeeper and run through a routine sample.
2. There are mega cases that we do QC together in BALSAMIC. So linking actual production samples are still a case.
3. I need some sort of a long-term stage and/or alternative analysis dir. And they should not be stored or added to trailblazer.

The complexity is just too much to make it work with Stage (multiple people use it during the day and analysis can take more than a day or two).

Any solution to assist me, Keyvan, and Ashwini doing above is appreciated.

**Comment by Mropat** [comment]
@hassanfa could you use stage environment for this? Perhaps if copying prod to stage was easier?

**Comment by hassanfa** [comment]
`stage` gets wiped though, doesn't it? For point 2 and 3, I'm doing on my own dev environment.

Using stage doesn't address point 1 though. Those are still production.

Lets allow this issue to simmer a bit, and look into what can be done.
