### ISSUE TITLE
Add CLI command to delete a user from the database

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/trailblazer#171]
## Description
We need to be able to remove users from the trailblazer database via CLI.

## Suggested solution
Add `trailblazer delete user [firstname.surname]` or similar

## This can be closed when
One can delete a user from the database via the CLI

**Comment by patrikgrenfeldt** [comment]
> Actually it would be even better with some API endpoints to handle CRUD operation and doing this from the front-end user interface by admin users. What do you think? @Mropat @patrikgrenfeldt @moedarrah @elevu

I think this is one area where [Flask](https://flask.palletsprojects.com/en/2.0.x/) i really awesome, you get an user interface without any development for basic data manipulation 😄
