### ISSUE TITLE
MIP-DNA cases almost dissapearing off the page

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/trailblazer#183]
We now have so many MIP-DNA cases to deliver that low priority cases are coming very close to not being shown anymore before completing. Below an example of the bottom of the page:

<img width="1368" alt="image" src="https://user-images.githubusercontent.com/57712924/194835963-6b29f7d3-030b-4b4e-99e2-735e8aef2791.png">

Would it be possible to show more cases?

**Comment by elevu** [comment]
I will fix it. Now 200 cases are shown, how many do you think it should be?

**Comment by karlnyr** [comment]
We are at a number now where we very seldom find ourselves. I thing doubling it would increase load time by a large margin, so perhaps a 50% increase would be appropriate?

**Comment by elevu** [comment]
The latest 300 analyses are now shown!

**Comment by peterpru** [comment]
Hi, not sure if I should reopen, or make a new issue. Below is a screenshot of mip reaching the bottom of the page again. This is filtered by low priority mip-dna samples only. This is mainly because of two tickets with about 50 research cases each in them.
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/57712924/199947655-07b439e3-73d4-4d57-bfba-9a8d47e839e7.png">

**Comment by elevu** [comment]
How many analyses should be shown?

**Comment by karlnyr** [comment]
@peterpru I think you can process these cases now, as for gameoryx the new and updated analysis has been submitted so it wont be missed. I think this still is an abnormal order and we should try to keep trailblazer as fast as possible.

**Comment by henrikstranneheim** [comment]
Seems resolved - closing
