### ISSUE TITLE
failed_jobs with status null

### ISSUE THREAD

**Issue by moedarrah** [Clinical-Genomics/trailblazer#235]
Some of the failed_jobs have a status null in:
 family: "petewe"
 id: 276060

https://trailblazer-api.scilifelab.se/api/v1/analyses?is_visible=true&query=&per_page=300

 
![Screenshot 2023-07-12 at 14 22 38](https://github.com/Clinical-Genomics/trailblazer/assets/41540288/3fba63f3-0148-4916-83c2-caab4d10996c)

**Comment by fevac** [comment]
All these jobs reported here with null status seemed to have been cached


>      task_id | process                                                                      | tag                    | status
>     ---------+------------------------------------------------------------------------------+------------------------+-----------
>      1       | NFCORE_RNAFUSION:RNAFUSION:INPUT_CHECK:SAMPLESHEET_CHECK                     | petewe_samplesheet.csv | CACHED
>      2       | NFCORE_RNAFUSION:RNAFUSION:CAT_FASTQ                                         | petewe                 | CACHED
>      3       | NFCORE_RNAFUSION:RNAFUSION:FASTQC                                            | petewe                 | CACHED
>      4       | NFCORE_RNAFUSION:RNAFUSION:TRIM_WORKFLOW:FASTP                               | petewe                 | CACHED
>      5       | NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STAR_FOR_STARFUSION           | petewe                 | CACHED
>      6       | NFCORE_RNAFUSION:RNAFUSION:FUSIONCATCHER_WORKFLOW:FUSIONCATCHER              | petewe                 | CACHED
>      7       | NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:STAR_FOR_ARRIBA                   | petewe                 | CACHED
>      8       | NFCORE_RNAFUSION:RNAFUSION:TRIM_WORKFLOW:FASTQC_FOR_FASTP                    | petewe                 | CACHED
>      9       | NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_SORT_FOR_ARRIBA          | petewe                 | CACHED
>      10      | NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:ARRIBA                            | petewe                 | CACHED
>      11      | NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_INDEX_FOR_ARRIBA         | petewe                 | CACHED
>      12      | NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_MARKDUPLICATES                 | petewe                 | FAILED
>      13      | NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:SAMTOOLS_INDEX_FOR_QC                 | petewe                 | CACHED
>      14      | NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:QUALIMAP_RNASEQ                       | petewe                 | FAILED
>      15      | NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:SAMTOOLS_INDEX_FOR_STARFUSION | petewe                 | CACHED
>      16      | NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:STARFUSION                    | petewe                 | CACHED
>      17      | NFCORE_RNAFUSION:RNAFUSION:ARRIBA_WORKFLOW:SAMTOOLS_VIEW_FOR_ARRIBA          | petewe                 | CACHED
>      18      | NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_COLLECTRNASEQMETRICS           | petewe                 | CACHED
>      19      | NFCORE_RNAFUSION:RNAFUSION:STARFUSION_WORKFLOW:SAMTOOLS_VIEW_FOR_STARFUSION  | petewe                 | CACHED
>      20      | NFCORE_RNAFUSION:RNAFUSION:FUSIONREPORT_WORKFLOW:FUSIONREPORT                | petewe                 | CACHED
>      21      | NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:FUSIONINSPECTOR          | petewe                 | CACHED
>      22      | NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:ARRIBA_VISUALISATION     | petewe                 | COMPLETED
>      23      | NFCORE_RNAFUSION:RNAFUSION:FUSIONINSPECTOR_WORKFLOW:MEGAFUSION               | petewe                 | COMPLETED
>      24      | NFCORE_RNAFUSION:RNAFUSION:CUSTOM_DUMPSOFTWAREVERSIONS                       |                        | COMPLETED
>      25      | NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:PICARD_MARKDUPLICATES                 | petewe                 | COMPLETED
>      26      | NFCORE_RNAFUSION:RNAFUSION:QC_WORKFLOW:QUALIMAP_RNASEQ                       | petewe                 | COMPLETED
>      27      | NFCORE_RNAFUSION:RNAFUSION:MULTIQC                                           |                        | COMPLETED
>

**Comment by fevac** [comment]
The issue is probably due to `TOWER_STATUS` not having defined the `CACHED` option
