### ISSUE TITLE
Wierd status of fluffy-jobs

### ISSUE THREAD

**Issue by karlnyr** [Clinical-Genomics/trailblazer#254]
There seem to be an issue with the status of jobs for fluffy:

<img width="1758" alt="image" src="https://github.com/Clinical-Genomics/trailblazer/assets/45558267/49cb9a54-4287-4de0-a3d9-e212952978a2">

This is a case which seems to be cancelled - however, the case has completed without issues on the cluster. Looking at the analysis close we can see:

<img width="1758" alt="image" src="https://github.com/Clinical-Genomics/trailblazer/assets/45558267/2a2a5812-182b-4fe2-89e0-d0293e2a6864">

and 

<img width="1758" alt="image" src="https://github.com/Clinical-Genomics/trailblazer/assets/45558267/657a3a50-444e-4457-bdec-3170146ee64c">

It would seem that for some jobs the status has been flipped, and perhaps set to canceled.

**Comment by karlnyr** [comment]
Yes - I saw it earlier this week as well - however I did set that analysis manually to complete

**Comment by henrikstranneheim** [comment]
Hmm, could you slack me next time you see it and leave it as is

**Comment by henrikstranneheim** [comment]
Could be that this return false when it should be true depending on the values from the get:
```
return bool(
        jobs_status_distribution.get(SlurmJobStatus.RUNNING)
        or jobs_status_distribution.get(SlurmJobStatus.PENDING)
    )
```
Maybe test for key existence instead, but not today....

**Comment by henrikstranneheim** [comment]
Done
