### ISSUE TITLE
trailblazer set-status not working anymore 

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/trailblazer#268]
The command `trailblazer set-status` is not working anymore. Probably coming from some current refactoring

### How to test:
 `trailblazer set-status --status failed cuddlyhen`

Outputs:
`cuddlyhen - Status set to FAILED`

However it does not update the status

**Comment by fevac** [comment]
unclear why this was happening but seems to be working with a different case. Closing. Will reopen if it appears again.

**Comment by fevac** [comment]
sorry for the back and forth this seems to be still an issue

**Comment by henrikstranneheim** [comment]
Starting a case:
```
Action running set for case justhusky
mip-dna run started!
 ```

<img width="1426" alt="Screenshot 2023-08-31 at 15 05 18" src="https://github.com/Clinical-Genomics/trailblazer/assets/584738/7a3e02db-7c5f-4820-94f9-f3d12e4f45cb">

Changing status:
```
θ72° [henrik.stranneheim@hasta:~] [S_base] 1m39s $ trailblazer set-status --status failed justhusky
justhusky - Status set to FAILED
```

<img width="1426" alt="Screenshot 2023-08-31 at 15 06 18" src="https://github.com/Clinical-Genomics/trailblazer/assets/584738/374ef3ae-f8ab-4f73-a8e9-63ef5a068a06">

**Comment by henrikstranneheim** [comment]
@fevac I cannot replicate the error. Can you provide some more details of when this occurs.

**Comment by henrikstranneheim** [comment]
Tested this multiple times and seems to always work. Closing - reopen if needed

**Comment by fevac** [comment]
Sorry I missed this notification. I can also replicate. Maybe it was something temporary or I was doing something wrong.
