### ISSUE TITLE
Analysis record doens't match current run

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/trailblazer#3]
Tried to delete following case, got an error:
`cust002-F0012102: analysis record doesn't match current run`

What does this mean?

**Comment by robinandeer** [comment]
It means the output on disk is not the same as the one that Trailblazer knows of.

Not sure but might be bc it's been rerun recently?

Shouldn't be a problem tho since the data for that analysis has been overwritten already

**Comment by ingkebil** [comment]
it seems plink has been run afterwards? I guess someone was trying to debug something about this analysis.

I'll close this.
