### ISSUE TITLE
Filtering in the webpage by cancelled not working due to spelling mistake

### ISSUE THREAD

**Issue by diitaz93** [Clinical-Genomics/trailblazer#313]
After changing the status "canceled" to "cancelled", the filtering in the web page was probably not updated, so it is impossible to show only cancelled cases, see screenshot: ![image](https://github.com/Clinical-Genomics/trailblazer/assets/11880814/8f73d5cc-082f-4c1f-bccd-b95692017606)

**Comment by seallard** [comment]
Resolved in https://github.com/Clinical-Genomics/cigrid-ui/pull/457
