### ISSUE TITLE
Speed up retrieving the latest failed job

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/trailblazer#324]
Implement something like https://github.com/Clinical-Genomics/trailblazer/pull/322 to return the latest failed job for an analysis. That implementation can be improved though (processing time 500 ms) by using lazy loading or batching the retrieval of the failed jobs. It is inefficient to run a separate query for each analysis to retrieve the latest failing job.

The latest failing job is displayed in cigrid when the user hovers on the failed status.

**Comment by seallard** [comment]
Requests are down to 100 ms

**Comment by henrikstranneheim** [comment]
🚀
