### ISSUE TITLE
Can we delete the Analysis.is_deleted column?

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/trailblazer#325]
## Description
I fail to understand what the is_deleted column is doing. It is set by the endpoint `/mark-analyses-deleted`. But I cannot see any logic using it. Not in Trailblazer, or any other repo in the Clinical-Genomics organisation

## Suggested solution
I need a second pair of eyes on this. If that person agrees. Remove the column, functions, and corresponding function in cg

**Comment by seallard** [comment]
The endpoint `mark-analyses-deleted` is actually called from cg. It is called when `add_pending_trailblazer_analysis` is called. However, there does not seem to be any logic that depends on the `is_deleted` attribute so I say we can delete it (but cg needs to be updated as well as to not call the endpoint).
