### ISSUE TITLE
Incorrect trailblazer status for tower analysis

### ISSUE THREAD

**Issue by fevac** [Clinical-Genomics/trailblazer#332]
I don’t think trailblazer is properly picking the status from tower. Currently we have XXX in production running. The status in tower gui is `running`  and the status retrieved by tower API is also `running`  but it’s being set as `error` in trailblazer. I temporarily changed  the TB status to `running`  (so it would be an ongoing analysis and updated again) but it sets it again as error. Any one has any idea of what could be the issue?

# Clarification
Analyses in trailblazer that are run using NF-tower (RNAFusion, Tomte) are being set to error in `trailblazer scan` when they should be set to running.

**Comment by seallard** [comment]
> @seallard Do you have time to take a look?

Sure, I can prioritise this. On first glance I have no clue what could be the issue

**Comment by henrikstranneheim** [comment]
@fevac Could you list the case and post the SLURM status of each job or point to the job status fike for @seallard?

**Comment by seallard** [comment]
Setting this to on hold until it reoccurs and we have more information or can reproduce the bug

**Comment by Vince-janv** [comment]
@fevac Is this problem still occurring?

**Comment by fevac** [comment]
I believe it's not happening anymore. Closing.
