### ISSUE TITLE
Fix filtering in the analyses endpoint

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/trailblazer#352]
## Description
Filtering analyses is not working well. When filtering on pipeline=fastq I get back RSYNCs, fluffy-cases and demultiplexes.
Also adding "balsamic" or any other pipeline in a comment will make it show up in every query including "balsamic"

## Suggested solution
- As a first step make data_delivery an option to pass to the endpoint and filter on.
- Add more filtering

**Comment by seallard** [comment]
The fastq-tab is only displaying fastq analyses - where is the filtering with the fastq pipeline not working?
