### ISSUE TITLE
Trailblazer monitors analyses through jobid files

### ISSUE THREAD

**Issue by emiliaol** [Clinical-Genomics/trailblazer#39]
Contact person: ES

As a production bioinformatician I want to be able to easily track the analysis progress of Balsamic runs so that I can react to problems and delivery ready data fast and efficiently.

**Problem description**: We have no way to monitor the analysis progress today. It would be nice to use a similar interface as we use for MIP analysis.

**Suggested solution for TB**:
As we can ask the pipelines to output a jobid _file_ for each case, TB can be made aware of the location of those files, for each pipeline! In that case, we know the pipeline, we know the case name, we know the location of the jobid file.

The jobids can then be used to query slurm (`scontrol show job $jobid`) to figure out the status, the start and stop time, the estimated time of completion, and thus also, the estimated time of completion of the case!

- [ ] tb can be passed locations of the jobid files (see below (*)).
- [ ] tb can query slurm
- [ ] tb backend can now parse and store the queried information (instead of the sacct file)
- [ ] tb's frontend can now display the stored information (should have)
- [ ] tb's frontend can now display the pipeline name and version. e.g. by expanding the version string to include the name of the pipeline (could have)
- [ ] tb has a cli command that can be called from a crontab to search for the jobid files

**Suggested solution for providing the jobid files:** (*) (see first checkbox above)
~~In a crontab script, we could `find` or glob all jobid files and pass them to tb. That list could be quite extensive, so it is preferred to invoke tb once for each jobid file.
The advantage of moving this complexity to the crontab file is that tb doesn't become pipeline aware! Meaning that tb doesn't need to know where to find MIP, BALSAMIC or uSALT jobid files. We could provide the jobid file, the pipeline, the pipeline version, and the case id to tb. To get the pipeline version, we would have to be able to parse e.g. sampleInfo file for a case (for MIP. Unknown what this would be for BALSAMIC).~~
~~e.g. `trailblazer monitor <case> --pipeline mip --version 6.0.1 --jobid-file <location>`~~
- [ ] ~~version info is parsed fomr sampleInfo file for MIP.~~
- [ ] ~~crontab file is written~~

-------
~~Alternative solution based on not having a jobid file and instead job ids are printed to screen (this is not a good solution and is only provided to not lose a previous idea):
- BALSAMIC/MIP/uSALT needs to produce a SLURM job id list. How this is done is up to the BALSAMIC dev team. Suggestions are:
  - create a file with job id list. One job id on each line.
  - when starting the pipeline, print out the job ids to STDOUT/ERR/log in a clearly marked sections so that it can be easily parsed.

- CG
  - [ ] needs to parse the job list and store it until the analysis is finished. Suggestion to create a new table to hold job ids linked to an analysis.
  - [ ] CLI to ask for the latest analysis, e.g. `cg get analysis`. Answers the question: what analysis have been run since .... Output: a yaml list of case ids.
  - [ ] CLI to ask for job list of the latest analysis or an analysis, e.g. `cg get analysis --name $case --with-job-ids`. It answers the question: give me the job list of the last X analysis or the analysis run since date YYYY-mm-dd. Output: a list yaml list (suggested output might be wrong):
```
- angrybird
  - 123146
  - 123147
- mutantturtle
  - 123148
  - 123149
```
- [ ] TB needs a CLI that accepts a job list file, e.g. `tb add job-ids --name $case-name $job-id-file
- [ ] ~~Create a crontab script that glues CG with TB: e.g. ~~
```
for ANALYSIS in $(cg get analysis --from $(date -d "-21days"  +'%Y-%m-%d'`)); do
    trailblazer add job-ids --name $ANALYSIS <(cg get analysis --name $ANALYSIS --with-job-ids)
done
```
- [ ] OR the above crontab is a meta interface in CG (preferred)~~
-----

- How to demo?
- DoD?
- Create US to mark a case as pending in TB from CG
- Create US to auto store balsamic analyses

**Comment by ingkebil** [comment]
refined ;)

**Comment by emiliaol** [comment]
Do we really need to change this for MIP 7? According to HS it's not much changed from mip 6 that's running now.

**Comment by ingkebil** [comment]
If we can still monitor an analysis the same way for both MIP6 and MIP7, than we do not need to have the jobid files functionality implemented.

Does MIP7 still have the sacct file @henrikstranneheim ?

**Comment by henrikstranneheim** [comment]
Yes, and also a list of job_ids that you wanted in another file (that is generated for all MIP pipelines). I guess this can wait until you are ready for a bigger refactoring of trailblazer with balsamic and microSalt.

**Comment by henrikstranneheim** [comment]
I would like to call this done! Would you not agree @Mropat?

**Comment by Mropat** [comment]
@henrikstranneheim definitely!
