### ISSUE TITLE
Refine and update Workflow status options

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/trailblazer#393]
# Description

For the project outlined in: https://github.com/Clinical-Genomics/project-planning/issues/453 we likely need to refine the trailblazer status updates for cases. 

- Identify the current flow of status updates for workflows in trailblazer
- identify required updates, if any.

**Comment by islean** [comment]
This sounds interesting also for the streamline delivery project where production have a need for seeing a status summary for the analyses within an order. These are not only related to Trailblazer statuses, and include statuses such as "lab prep" as well. Latest suggestion we had there were the following options (to be refined is which should be in Trailblazer and which should be inferred from the data in status db):

-- Lab
Total
Not received (useful if some samples have been received but others not yet)
Lab steps - when Received at is set
Sequencing - Is it possible to set Sequence start from LIMS?
(Demultiplexing - not a status as it is not possible to determine now)
-- Bioinfo
Running - when analysis starts
Completed or Failed
Uploaded or Upload failed
Delivered

**Comment by ChrOertlin** [comment]
> -- Lab
> Total
> Not received (useful if some samples have been received but others not yet)
> Lab steps - when Received at is set
> Sequencing - Is it possible to set Sequence start from LIMS?
> (Demultiplexing - not a status as it is not possible to determine now)
> -- Bioinfo
> Running - when analysis starts
> Completed or Failed
> QC Pass or Fail
> Uploaded or Upload failed
> Delivered

We need one more step for the QC checks in here

**Comment by diitaz93** [comment]
Closing as was taken over in the streamline delivery project
