### ISSUE TITLE
TB  validated on Hasta

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/trailblazer#42]
As a production bioinformatician I want TB to be up and running so that I am able to monitor and start mip analysis on hasta.

Problem: MIP is installed but we have no way to start or monitor analysis started via cg right now on Hasta. We need the website (trailblazer-stage.scilifelab.se) to pick this up from the analysis on Hasta.

Suggested solution:

1. Test case to be documented in new issue in servers on github (use tag for hasta verification):
 - use ~~solidmoose hapmap sample vitalmouse (trio), ADM1059A5 (single) as test case~~ grownliger
 - as production user on hasta
 - copy grownliger
 - trailblazer scan -> on https://trailblazer-stage.scilifelab.se/ the case grownliger should show up as finished/or ```trailblazer ls```
 - remove grownliger from TB-stage
 - add TB scan to the crontab (take it from rasta's crontab)
 - on https://trailblazer-stage.scilifelab.se/ the case grownliger should show up as finished/or ```trailblazer ls```

2. Write an implementation plan.
reference the issue where you put the test case that's the issue
inform relevant staff
and other things in the implementation plan template

DoD:
See test case

How to demo:
- remove case grownliger case from trailblazer-stage db
- on hasta as any prod user run "trailblazer scan"
- Go to https://trailblazer-stage.scilifelab.se/ and show the analysis!

**Comment by emiliaol** [comment]
https://github.com/Clinical-Genomics/servers/issues/78

**Comment by emiliaol** [comment]
I think we should discuss if we shouldn't just include the implementation of TB in the rare disease pipeline implementation (https://zube.io/clinical-genomics/pbl-team-lessteamnamegreater/c/2385) because that is where we can update the crontab and monitor the analysis running on hasta. 
@ingkebil @barrystokman What say you?

**Comment by ingkebil** [comment]
Do you mena, we could fill in TB's implementation plan now and send it together with the rare disease validation? If so, sure!
