### ISSUE TITLE
approve housekeeper for use on hasta

### ISSUE THREAD

**Issue by barrystokman** [Clinical-Genomics/trailblazer#43]
add/get bundles and add files to bundles

As a IT person at CG I want to be able to store analysis results and fastq links in HK for future use.

Problem: We cannot use the installation of HK  on Hasta until we have verified that it work in a production like setting.

Suggested solution:

1. Test case to be documented in new issue in servers on github (use tag for hasta verification):
 - remove solidmoose from HK-stage
 - remove the completed at date in statusdb (stage) for solidmoose: analysis tab
 - use solidmoose as test case
 - as production user on hasta
 - cg store completed -> add the analysis files from solidmoose to the HK db and file structure (/home/proj/stage/housekeeper-bundles/solidmoose) on hasta 
 - housekeeper get -V solidmoose -> lists the links/files in the HK db for solidmoose

2. Write an implementation plan.
 - reference the issue
 - inform relevant staff
 - and other things in the implementation plan template

DoD:
See test case

How to demo:
solidmoose has to be completed in TB
restore the stage HK db on clinical db ($ /home/hiseq.clinical/servers/resources/clinical-db/dbcopy-prod-to-stage.sh  housekeeper
remove the completed at date in statusdb (stage) for solidmoose: analysis tab

on hasta:
cg store completed
housekeeper get -V solidmoose -> lists the links/files in the HK db for solidmoose

**Comment by patrikgrenfeldt** [comment]
@barrystokman, @emiliaol should this issue be in the HK repo instead?

**Comment by barrystokman** [comment]
Yes, use https://github.com/Clinical-Genomics/housekeeper/issues/46 now instead.
