### ISSUE TITLE
Confusing flags for delivered cases

### ISSUE THREAD

**Issue by ChrOertlin** [Clinical-Genomics/trailblazer#452]
When looking at this order https://cigrid.scilifelab.se/orders/10398 
We can see that it is delivered with a sample that failed qc.

The failed QC flag together with the delivered flag causes confusion.

# Acceptance Criteria

- [ ] Do not display failed seq qc. if case is delivered.

# Implementation plan

1. When generating status summaries, any trailblazer statuses should override statusDB statuses.

**Comment by ChrOertlin** [comment]
# Refinement meeting 12-06-2024

The delivered flag should override other existing flags, thus a DELVIVERED flag should not be able to be co-displayed with a FAILED SEQ. QC flag.

**Comment by islean** [comment]
Trailblazer statuses should run supreme now. Please reopen if cases are counted doubly still.
