### ISSUE TITLE
Error when delivery message is for fastq/analysis

### ISSUE THREAD

**Issue by peterpru** [Clinical-Genomics/trailblazer#456]
When Data Delivery is fastq-analysis, then clicking Copy delivery message gives an error, and no delivery message is generated.

<img width="327" alt="image" src="https://github.com/Clinical-Genomics/trailblazer/assets/57712924/8e33fc7b-7974-44ed-9a8e-b4f1fae061a5">

**Comment by Vince-janv** [comment]
Error reproduced for same case

**Comment by diitaz93** [comment]
# Technical refinement:
Fin and patch the relevant delivery message in https://github.com/Clinical-Genomics/cg/tree/master/cg/services/delivery_message/messages
