### ISSUE TITLE
Handle different MIP versions

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/trailblazer#46]
AS A production user 
I WANT Trailblazer to handle different MIP versions 
SO THAT I can create delivery reports for older analyses than the current one

Suggested solution: 
Have different versions of the MIP/files.py that can handle data of different versions of the analysis fiiles, create one per commit to the files.py?

Example: functions can be invoked dynamically like so:
```       
order_func = getattr(self, f"submit_{project.value}")
result = order_func(data)
```

**Comment by henrikstranneheim** [comment]
This has now been done in: #99 #109 #107

**Comment by henrikstranneheim** [comment]
Although with a completely different solution
