### ISSUE TITLE
Upload date set for analyses even when RSYNC job fails

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/trailblazer#468]
Reported by @beatrizsavinhas

Analyses for cases in which `data_delivery` includes `fastq` or `analysis` still receive an `uploaded_at` date even when the rsync job fails. Effectively, the upload fails quietly and the analysis appears as if it was delivered in StatusDB and Trailblazer.

**Comment by beatrizsavinhas** [comment]
Updated the title and description!

Unfortunately I don't have an example at hand, but could we check or implement a check to prevent the upload date being set if the rsync job fails?

**Comment by seallard** [comment]
The bug needs to be reproduced and understood before we introduce any code for it.

**Comment by diitaz93** [comment]
Closing in favour of https://github.com/Clinical-Genomics/cg/issues/3842
