### ISSUE TITLE
Job profiling through hdf5 on hasta

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/trailblazer#47]
AS A bioinformatician
I WANT to profile resource usage for my analysis
SO THAT I can avoid using more than necessary resources (core/memory) for each bioinformatic tool

Suggested solution:
An creation of `check.py` or something similar to trailblazer/trailblazer/mip/ to run `sh5util -j jobid -p <path>` to profile resource usage for jobs with active `--profile` enabled.

Extra information:
Q: Does this work on old jobs?
A: No. Currently slurm config on Hasta deletes all node step information after certain amount of time, so this has to run _right_ after the job is finished, or we won't be able to profile it. (Edit: I looked into this, and I don't think jobminage is the issue, but node-step files are being deleted which I didn't have time too look into. I can dig more and find out about it).

Q: What are resources and manuals that can help with this issue?
A: For `sh5util`: https://slurm.schedmd.com/sh5util.html for `hdf5`profile guide: https://slurm.schedmd.com/hdf5_profile_user_guide.html for `sbatch --profile=task` manual: https://slurm.schedmd.com/sbatch.html

**Comment by emiliaol** [comment]
@ingkebil Something for TTN?

**Comment by ingkebil** [comment]
Yes, we can take this. It seems very appropriate for TBs new functionality.

Currently, `trailblazer scan` is only run every hour or so, this would have to be run much more frequently.
