### ISSUE TITLE
SPIKE: Does TB monitor MIP7 slurm

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/trailblazer#54]

**Comment by emiliaol** [comment]
@ingkebil Did you start looking into this, and if you did, what did you find?

**Comment by ingkebil** [comment]
Haven't looked into this. Please ask someone else to take a look at this.

There is some explanation here: 
- https://github.com/Clinical-Genomics/trailblazer/blob/master/README.md
- https://github.com/Clinical-Genomics/MIP/issues/777

Please request changes from MIP if needed

**Comment by ingkebil** [comment]
Sorry for only turning up with this now: I had looked at this in december :D

https://github.com/Clinical-Genomics/trailblazer/issues/39
